name: build-and-push

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: 'Create .env file'
        run: |
          touch .env
          echo PORT=${{ vars.PORT }} >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }} >> .env
          echo PAYLOAD_PUBLIC_SITE_NAME=${{ secrets.PAYLOAD_PUBLIC_SITE_NAME }} >> .env
          echo PAYLOAD_PUBLIC_SERVER_URL=${{ secrets.PAYLOAD_PUBLIC_SERVER_URL }} >> .env
          echo PAYLOAD_PUBLIC_FRONTEND_URL=${{ secrets.PAYLOAD_PUBLIC_FRONTEND_URL }} >> .env
          echo PAYLOAD_PUBLIC_LOCALE_DEFAULT=${{ secrets.PAYLOAD_PUBLIC_LOCALE_DEFAULT }} >> .env
          echo PAYLOAD_PUBLIC_LOCALE_LIST=${{ secrets.PAYLOAD_PUBLIC_LOCALE_LIST }} >> .env
          echo PAYLOAD_PUBLIC_DRAFT_SECRET=${{ secrets.PAYLOAD_PUBLIC_DRAFT_SECRET }} >> .env
          echo REVALIDATION_KEY=${{ secrets.REVALIDATION_KEY }} >> .env
          echo GOOGLE_RECAPTCHA_SECRET=${{ secrets.GOOGLE_RECAPTCHA_SECRET }} >> .env
          echo SMTP_FROM_EMAIL=${{ secrets.SMTP_FROM_EMAIL }} >> .env
          echo SMTP_ADMIN_EMAIL=${{ secrets.SMTP_ADMIN_EMAIL }} >> .env
          echo SMTP_HOST=${{ secrets.SMTP_HOST }} >> .env
          echo SMTP_PORT=${{ secrets.SMTP_PORT }} >> .env
          echo SMTP_USER=${{ secrets.SMTP_USER }} >> .env
          echo SMTP_PASS=${{ secrets.SMTP_PASS }} >> .env

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
